### ISSUE TITLE
About some problem

### ISSUE THREAD

**Issue by kumfo** [henricavalcante/openomr#1]
My English proficiency is not good,I don't know Could you understand the issues which I say. I use download your code and test,I find it need the Imagick lib,and I download a new Imagick Lib from internet, and i also config the "php.ini",but the Imagick Lib no effect.what does the version of the php which you using?could you tell me?

**Comment by henricavalcante** [comment]
tested on php 5.4 and php 5.5.

Can you give a error message?

**Comment by kumfo** [comment]
Error output "Fatal error: Class 'Imagick' not found in E:\wamp\www\test\openomr-master\openomr.php on line 23",but I already config the php.ini import the "php_imagick.dll",I test it under the php 5.3,but I reedit the code to fit the php 5.3(___),Thank you.

**Comment by kumfo** [comment]
Error output "Fatal error: Class 'Imagick' not found in E:\wamp\www\test\openomr-master\openomr.php on line 23",but I already config the php.ini import the "php_imagick.dll",I test it under the php 5.3,but I reedit the code to fit the php 5.3(*_*),Thank you.

**Comment by henricavalcante** [comment]
Feel free to pull request any improvement on code.
